version: '3'

services:

  trainer:
    build: ../../keras-accent-trainer # maps the directory that contains the Dockerfile
    image: keras-accent-training
    container_name:  accent_predictor_trainerls -l 
    command: "python accent_dataset/create.py && python run_from_config.py -c configs/usa_english_speakers.json"
    volumes: 
      - /share/datasets:/app/datasets
      - /share/saved_models:/app/saved_models


