version: '3'

services:

  uk_predictor:
    build: ../../keras-accent-trainer # maps the directory that contains the Dockerfile
    image: keras-accent-training
    command: "python webserver/serve.py"
    ports:
      - "8080:8080"
    volumes: 
      - /share/uploads:/app/webserver/uploads

  usa_predictor:
    build: ../../keras-accent-trainer # maps the directory that contains the Dockerfile
    image: keras-accent-training
    command: "python webserver/serve.py"
    ports:
      - "8081:8080"
    volumes:
      - /share/uploads:/app/webserver/uploads

  # change to have everything in one docker
  bot:
    build: ../../accent-bot # maps the directory that contains the Dockerfile
    image: bot
    container_name: telegram_bot
    command: "python src/accent_bot/run.py"
    environment:
      - BOT_ID=XXXX
    ports:
      - "0.0.0.0:80:80"
    depends_on: 
      - usa_predictor
      - uk_predictor
