version: '3'

services:

  bot:
    environment:
      - BOT_ID=874455740:AAF-ipcxqBYcvzBkTS16TKLYCPqkPCcytw0

  usa_predictor:
    environment:
      - MODEL_TYPE=usa_english_speakers
      - MODEL_NUM=cc1ab98bec194d9b8fbbe3ecb21c95d6

  uk_predictor:
    environment:
      - MODEL_TYPE=uk_target_only_native_speakers
      - MODEL_NUM=1920d9ab03f540d5a04d4f82c5e57199