version: '3'

services:

  predictor:
    build: ../../keras-accent-trainer # maps the directory that contains the Dockerfile
    image: keras-accent-training
    container_name:  accent_predictor
    command: "python webserver/serve.py"
    environment: 
      - PORT=8080
      - HOST=0.0.0.0
      - MODEL_TYPE=usa_english_speakers
      - MODEL_NUM=4089305544804f5689faf7cce3e84258
    ports:
      - "8080:8080"
    volumes: 
      - /share/uploads:/app/webserver/uploads

  # change to have everything in one docker
  bot:
    build: ../../accent-bot # maps the directory that contains the Dockerfile
    image: bot
    container_name: telegram_bot
    command: "python src/accent_bot/run.py"
    environment:
      - PREDICTION_API=http://predictor:8080
      - BOT_ID=XXXX
    ports:
      - "0.0.0.0:80:80"
    depends_on: 
      - predictor
